name: DBC

services:
  # frontend:
  #   container_name: BIBA_FRONTEND
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - /app/frontend/node_modules
  #   environment:
  #     - FE_PORT=3000
  #     - CHOKIDAR_USEPOLLING=true
  #   command: yarn dev

  backend:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./backend
    volumes:
      - /app/backend/node_modules
      - ./backend/dist:/app/backend/dist
    ports:
      - ${BE_PORT}:${BE_PORT}
    command: node dist/src/main
    environment:
      - NODE_ENV=${NODE_ENV}
      - BE_PORT=${BE_PORT}
      - FALLBACK_LANGUAGE=${FALLBACK_LANGUAGE}
      - OWN_URL=${OWN_URL}
      - POSTGRE_URL=${POSTGRE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
