[project]
name = "mlservice"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "antlr4-tools>=0.2.2",
    "fastapi[standard]>=0.115.14",
    "pydantic-settings>=2.10.1",
    "pygithub>=2.6.1",
    "sqlglot[rs]>=26.33.0",
]
